<?php

declare(strict_types=1);

namespace App\Services\Hira;

/**
 * Contoh data awal (sama dengan desain.html INITIAL_ROWS).
 *
 * @return list<array<string, mixed>>
 */
final class HiraImprovementDetailSampleData
{
    public static function rows(): array
    {
        return [
            ['improvement_plan' => 'Interlock Seatbelt Unit HD dan LV', 'section' => 'Section Operation', 'activity' => 'Operasi unit HD', 'sub_activity' => 'Start dan hauling HD', 'sub_sub_activity' => 'Seatbelt interlock saat unit bergerak', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Men', 'hazard' => 'Operator HD mengoperasikan unit tanpa seatbelt', 'event_potential' => 'GR No. 2 Seatbelt; potensi fatality/serious injury saat collision atau rollover', 'kep_awal' => 4, 'konseq_awal' => 5, 'tp_awal' => 'ADM', 'existing_control' => 'SOP, inspeksi harian, safety talk, pengawasan penggunaan seatbelt', 'owner_existing' => 'Operation / Safety', 'control_level' => 'L2 - Mencegah', 'exposure_type' => 'Unit', 'exposure_before_value' => 96, 'exposure_control_value' => 96, 'kep_sisa' => 1, 'konseq_sisa' => 5, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Safety Engineering / Operation', 'start_date' => '2026-01-01', 'target_date' => '2026-06-30', 'status' => 'Implemented'],
            ['improvement_plan' => 'Interlock Seatbelt Unit HD dan LV', 'section' => 'Section Plant', 'activity' => 'Instalasi dan maintenance interlock HD', 'sub_activity' => 'Preventive maintenance sistem seatbelt interlock', 'sub_sub_activity' => 'Pengecekan sensor, wiring, dan engine interlock HD', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Mac', 'hazard' => 'Interlock seatbelt gagal fungsi karena kerusakan sensor atau wiring', 'event_potential' => 'Unit tetap dapat beroperasi tanpa seatbelt akibat bypass/failure interlock', 'kep_awal' => 3, 'konseq_awal' => 5, 'tp_awal' => 'ADM', 'existing_control' => 'Checklist P2H, inspeksi elektrik, corrective maintenance jika ditemukan abnormality', 'owner_existing' => 'Plant / Maintenance', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Unit', 'exposure_before_value' => 96, 'exposure_control_value' => 80, 'kep_sisa' => 2, 'konseq_sisa' => 5, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Plant / Safety Engineering', 'start_date' => '2026-01-01', 'target_date' => '2026-07-31', 'status' => 'In Progress'],
            ['improvement_plan' => 'Interlock Seatbelt Unit HD dan LV', 'section' => 'Section Operation', 'activity' => 'Operasi unit LV', 'sub_activity' => 'Mobilisasi LV di jalan tambang', 'sub_sub_activity' => 'Seatbelt interlock saat mobilisasi LV', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Men', 'hazard' => 'Operator atau penumpang LV tidak menggunakan seatbelt', 'event_potential' => 'Cedera serius/fatality saat collision, rollover, atau sudden braking', 'kep_awal' => 4, 'konseq_awal' => 5, 'tp_awal' => 'ADM', 'existing_control' => 'SOP mobilisasi, inspeksi LV, safety campaign, pengawasan lapangan', 'owner_existing' => 'Operation / Safety', 'control_level' => 'L2 - Mencegah', 'exposure_type' => 'Unit', 'exposure_before_value' => 52, 'exposure_control_value' => 52, 'kep_sisa' => 1, 'konseq_sisa' => 5, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Safety Engineering / Operation', 'start_date' => '2026-01-01', 'target_date' => '2026-06-30', 'status' => 'Implemented'],
            ['improvement_plan' => 'Interlock Seatbelt Unit HD dan LV', 'section' => 'Section HSE', 'activity' => 'Validasi kepatuhan seatbelt', 'sub_activity' => 'Monitoring pelanggaran GR No. 2 Seatbelt', 'sub_sub_activity' => 'Audit sampling dan verifikasi trend pelanggaran seatbelt', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Met', 'hazard' => 'Efektivitas interlock tidak tervalidasi secara periodik', 'event_potential' => 'Pelanggaran seatbelt berulang tidak terdeteksi sebagai tren sistemik', 'kep_awal' => 3, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'Audit GR, observasi lapangan, review trend pelanggaran', 'owner_existing' => 'HSE / Operation', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Man Hour', 'exposure_before_value' => 480, 'exposure_control_value' => 360, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ADM', 'owner_lanjutan' => 'HSE', 'start_date' => '2026-01-01', 'target_date' => '2026-12-31', 'status' => 'In Progress'],
            ['improvement_plan' => 'CCTV Analytic Workshop Area', 'section' => 'Section Plant', 'activity' => 'Aktivitas maintenance workshop', 'sub_activity' => 'Pekerjaan mekanik di bay workshop', 'sub_sub_activity' => 'Deteksi unsafe act/unsafe condition melalui CCTV analytic', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Men', 'hazard' => 'Unsafe act di workshop terlambat terdeteksi', 'event_potential' => 'First Aid / TTA akibat kontak dengan alat, pinch point, atau line of fire', 'kep_awal' => 3, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'CCTV existing, inspeksi workshop, pengawasan area kerja', 'owner_existing' => 'Plant / Workshop / Safety', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Unit', 'exposure_before_value' => 1, 'exposure_control_value' => 1, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Safety Engineering / Transformasi', 'start_date' => '2026-01-01', 'target_date' => '2026-06-30', 'status' => 'Implemented'],
            ['improvement_plan' => 'CCTV Analytic Workshop Area', 'section' => 'Section Plant', 'activity' => 'Aktivitas maintenance workshop', 'sub_activity' => 'Housekeeping dan traffic workshop', 'sub_sub_activity' => 'Analytic detection untuk area kerja tidak aman', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Env', 'hazard' => 'Area kerja workshop tidak aman atau tidak rapi tidak cepat terdeteksi', 'event_potential' => 'Slip/trip/fall, tertabrak manuver unit, atau paparan line of fire', 'kep_awal' => 3, 'konseq_awal' => 3, 'tp_awal' => 'ADM', 'existing_control' => '5R workshop, inspeksi harian, pengawasan supervisor', 'owner_existing' => 'Plant / Workshop', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Man Hour', 'exposure_before_value' => 720, 'exposure_control_value' => 720, 'kep_sisa' => 2, 'konseq_sisa' => 3, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Plant / Transformasi', 'start_date' => '2026-01-01', 'target_date' => '2026-06-30', 'status' => 'Implemented'],
            ['improvement_plan' => 'CCTV Analytic Workshop Area', 'section' => 'Section HSE', 'activity' => 'Validasi model AI CCTV', 'sub_activity' => 'Review detection accuracy', 'sub_sub_activity' => 'Sampling false positive dan false negative CCTV analytic', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Met', 'hazard' => 'Model AI tidak akurat sehingga unsafe condition tidak terbaca', 'event_potential' => 'Kondisi berisiko tetap terjadi karena alert tidak valid atau tidak ditindaklanjuti', 'kep_awal' => 3, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'Review manual CCTV, inspeksi fisik, laporan temuan pengawas', 'owner_existing' => 'HSE / Transformasi', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Man Hour', 'exposure_before_value' => 160, 'exposure_control_value' => 120, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ADM', 'owner_lanjutan' => 'HSE / Transformasi', 'start_date' => '2026-01-01', 'target_date' => '2026-09-30', 'status' => 'In Progress'],
            ['improvement_plan' => 'Workshop Activity Monitoring by BeSigma', 'section' => 'Section Plant', 'activity' => 'Aktivitas workshop', 'sub_activity' => 'Monitoring aktivitas mekanik', 'sub_sub_activity' => 'Trial BeSigma untuk monitoring pekerjaan mekanik', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Met', 'hazard' => 'Aktivitas mekanik tidak termonitor secara real time', 'event_potential' => 'Deviasi pekerjaan terlambat diketahui dan berpotensi First Aid/TTA', 'kep_awal' => 3, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'Monitoring manual, inspeksi area, briefing sebelum pekerjaan', 'owner_existing' => 'Workshop / Safety', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Man Power', 'exposure_before_value' => 42, 'exposure_control_value' => 28, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Transformasi / Safety', 'start_date' => '2026-01-01', 'target_date' => '2026-06-30', 'status' => 'In Progress'],
            ['improvement_plan' => 'Workshop Activity Monitoring by BeSigma', 'section' => 'Section Operation', 'activity' => 'Aktivitas pit support', 'sub_activity' => 'Koordinasi pekerjaan support di pit', 'sub_sub_activity' => 'Monitoring BeSigma untuk aktivitas support di pit', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Met', 'hazard' => 'Aktivitas support pit tidak termonitor dan tidak sinkron dengan kondisi lapangan', 'event_potential' => 'Interaksi tidak aman antara personel, unit, dan area kerja aktif', 'kep_awal' => 3, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'Koordinasi radio, briefing, pengawasan supervisor', 'owner_existing' => 'Operation / Safety', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Man Hour', 'exposure_before_value' => 320, 'exposure_control_value' => 160, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Transformasi / Operation', 'start_date' => '2026-01-01', 'target_date' => '2026-12-31', 'status' => 'In Progress'],
            ['improvement_plan' => 'Workshop Activity Monitoring by BeSigma', 'section' => 'Section HSE', 'activity' => 'Validasi training BeSigma', 'sub_activity' => 'Training dan adoption user', 'sub_sub_activity' => 'Progress training bersama BC', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Men', 'hazard' => 'User belum konsisten menggunakan BeSigma untuk monitoring aktivitas', 'event_potential' => 'Sistem monitoring tidak efektif karena adoption belum merata', 'kep_awal' => 3, 'konseq_awal' => 3, 'tp_awal' => 'ADM', 'existing_control' => 'Training awal, coaching, sosialisasi penggunaan sistem', 'owner_existing' => 'HSE / Transformasi', 'control_level' => 'L5 - Deteksi Manual', 'exposure_type' => 'Man Power', 'exposure_before_value' => 30, 'exposure_control_value' => 18, 'kep_sisa' => 2, 'konseq_sisa' => 3, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ADM', 'owner_lanjutan' => 'Transformasi / HSE', 'start_date' => '2026-01-01', 'target_date' => '2026-09-30', 'status' => 'In Progress'],
            ['improvement_plan' => 'Warning Dump Unit DTMB', 'section' => 'Section Operation', 'activity' => 'Aktivitas dumping DTMB', 'sub_activity' => 'Positioning dan raising vessel', 'sub_sub_activity' => 'Warning dump untuk mencegah human error operator', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Men', 'hazard' => 'Human error saat dumping / PD vessel tersangkut', 'event_potential' => 'PD vessel tersangkut, property damage, downtime, dan potensi injury', 'kep_awal' => 4, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'SOP dumping, spotter, inspeksi area, komunikasi operator', 'owner_existing' => 'Operation', 'control_level' => 'L2 - Mencegah', 'exposure_type' => 'Unit', 'exposure_before_value' => 100, 'exposure_control_value' => 100, 'kep_sisa' => 1, 'konseq_sisa' => 4, 'target_risk' => 'Low', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'PMR 1-3 / Operation', 'start_date' => '2026-01-01', 'target_date' => '2026-06-30', 'status' => 'Verified Effective'],
            ['improvement_plan' => 'Warning Dump Unit DTMB', 'section' => 'Section Plant', 'activity' => 'Maintenance warning dump DTMB', 'sub_activity' => 'Pemeriksaan buzzer, sensor, dan indikator warning', 'sub_sub_activity' => 'Preventive maintenance warning dump system', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Mac', 'hazard' => 'Warning dump tidak aktif karena kerusakan alat atau wiring', 'event_potential' => 'Operator tidak menerima peringatan saat dumping sehingga human error tidak dicegah', 'kep_awal' => 3, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'P2H, inspeksi elektrik, corrective maintenance', 'owner_existing' => 'Plant / Maintenance', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Unit', 'exposure_before_value' => 100, 'exposure_control_value' => 85, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Plant / PMR 1-3', 'start_date' => '2026-01-01', 'target_date' => '2026-08-31', 'status' => 'In Progress'],
            ['improvement_plan' => 'Warning Dump Unit DTMB', 'section' => 'Section HSE', 'activity' => 'Validasi efektivitas warning dump', 'sub_activity' => 'Audit perilaku dumping dan event PD vessel', 'sub_sub_activity' => 'Review trend PD vessel tersangkut dan kepatuhan SOP dumping', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Met', 'hazard' => 'Efektivitas warning dump tidak tervalidasi terhadap trend kejadian', 'event_potential' => 'PD vessel tersangkut berulang tanpa corrective action sistemik', 'kep_awal' => 3, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'Investigasi event, review dashboard, coaching operator', 'owner_existing' => 'HSE / Operation', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Man Hour', 'exposure_before_value' => 240, 'exposure_control_value' => 160, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ADM', 'owner_lanjutan' => 'HSE / Operation', 'start_date' => '2026-01-01', 'target_date' => '2026-12-31', 'status' => 'In Progress'],
            ['improvement_plan' => 'Alert Covering Camera Speed 0', 'section' => 'Section Operation', 'activity' => 'Operasi unit dengan DMS', 'sub_activity' => 'Monitoring camera covering dan speed 0', 'sub_sub_activity' => 'Alert saat kamera tertutup dan unit speed 0', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Men', 'hazard' => 'Kamera DMS ditutup sehingga fatigue/distraction tidak termonitor', 'event_potential' => 'GR No. 1 Menutup Kamera; fatigue/distraction tidak terdeteksi dan berpotensi incident', 'kep_awal' => 4, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'DMS monitoring, inspeksi, coaching operator, konfigurasi alert existing', 'owner_existing' => 'Operation / Safety', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Unit', 'exposure_before_value' => 108, 'exposure_control_value' => 54, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Safety Engineering', 'start_date' => '2026-01-01', 'target_date' => '2026-12-31', 'status' => 'In Progress'],
            ['improvement_plan' => 'Alert Covering Camera Speed 0', 'section' => 'Section Plant', 'activity' => 'Maintenance DMS dan buzzer alert', 'sub_activity' => 'Pemeriksaan speaker buzzer dan konfigurasi speed 0', 'sub_sub_activity' => 'Replikasi speaker buzzer pada unit target', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Mac', 'hazard' => 'Speaker buzzer atau konfigurasi alert covering tidak berfungsi', 'event_potential' => 'Operator tidak menerima peringatan saat kamera tertutup sehingga covering berulang', 'kep_awal' => 3, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'Inspeksi DMS, pengecekan device, corrective maintenance vendor', 'owner_existing' => 'Plant / DMS Vendor', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Unit', 'exposure_before_value' => 108, 'exposure_control_value' => 54, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ENG', 'owner_lanjutan' => 'Plant / Safety Engineering', 'start_date' => '2026-01-01', 'target_date' => '2026-12-31', 'status' => 'In Progress'],
            ['improvement_plan' => 'Alert Covering Camera Speed 0', 'section' => 'Section HSE', 'activity' => 'Validasi pelanggaran camera covering', 'sub_activity' => 'Monitoring GR No. 1 Menutup Kamera', 'sub_sub_activity' => 'Review event covering speed 0 dan tindak lanjut coaching', 'rnr' => 'R', 'site' => 'HO', 'faktor' => 'Met', 'hazard' => 'Alert covering tidak ditindaklanjuti menjadi koreksi perilaku', 'event_potential' => 'GR No. 1 Menutup Kamera berulang dan fatigue monitoring tidak efektif', 'kep_awal' => 3, 'konseq_awal' => 4, 'tp_awal' => 'ADM', 'existing_control' => 'Review event DMS, coaching, progressive discipline, dashboard GR', 'owner_existing' => 'HSE / Operation', 'control_level' => 'L3 - Mendeteksi + Intervensi Manusia', 'exposure_type' => 'Man Hour', 'exposure_before_value' => 360, 'exposure_control_value' => 180, 'kep_sisa' => 2, 'konseq_sisa' => 4, 'target_risk' => 'Medium', 'tp_lanjutan' => 'ADM', 'owner_lanjutan' => 'HSE / Operation', 'start_date' => '2026-01-01', 'target_date' => '2026-12-31', 'status' => 'In Progress'],
        ];
    }
}
