@extends('pilot-project-validation.layout.peer-app')
@section('title', 'PPV - Tambah Metric')
@section('content')
<div class="bg-white rounded-2xl anchored-card overflow-hidden max-w-5xl">
<div class="p-6 border-b border-outline-variant/20"><h2 class="font-headline font-bold text-xl text-on-surface">Tambah Metric</h2></div>
<div class="p-6"><form method="POST" action="{{ route('pilot-project-validation.metrics.store') }}" class="grid grid-cols-1 gap-4 md:grid-cols-2">
@csrf
<div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Gate</label><select name="gate_id" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm">@foreach($gates as $g)<option value="{{ $g->id }}">{{ $g->project?->project_name }} | {{ $g->gate_label }} | {{ $g->gate_title }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Sort</label><input name="sort_order" value="0" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Critical</label><select name="critical" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"><option value="0">No</option><option value="1">Yes</option></select></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Metric Name</label><input name="metric_name" required class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Metric Type</label><input name="metric_type" value="range" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Direction</label><input name="direction" value="high" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Unit</label><input name="unit" value="%" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Metric Value</label><input name="metric_value" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Pass</label><input type="number" step="0.0001" name="pass_threshold" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Conditional</label><input type="number" step="0.0001" name="conditional_threshold" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Min</label><input type="number" step="0.0001" name="min_value" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Max</label><input type="number" step="0.0001" name="max_value" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Step</label><input type="number" step="0.0001" name="step_value" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Metric Status</label><input name="metric_status" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Metric Desc</label><textarea name="metric_desc" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></textarea></div>
<div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">PIC Current Finding</label><textarea name="pic_current_finding" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></textarea></div>
<div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">PIC Evidence Source</label><textarea name="pic_evidence_source" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></textarea></div>
<div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">PIC Comment</label><textarea name="pic_comment" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></textarea></div>
<div class="md:col-span-2 flex gap-2 pt-2"><button class="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-xs font-bold text-white shadow-md">Simpan</button> <a href="{{ route('pilot-project-validation.metrics.index') }}" class="inline-flex items-center gap-2 rounded-xl border border-outline-variant/30 bg-white px-4 py-2 text-xs font-bold shadow-sm hover:bg-surface-container-high">Batal</a></div>
</form></div></div>
@endsection

