@extends('peer-pressure-edukasi.layouts.peer-app')
@section('title', 'PPV - Edit Timeline Task')
@section('content')
<div class="bg-white rounded-2xl anchored-card overflow-hidden max-w-5xl">
<div class="p-6 border-b border-outline-variant/20"><h2 class="font-headline font-bold text-xl text-on-surface">Edit Timeline Task</h2></div>
<div class="p-6"><form method="POST" action="{{ route('pilot-project-validation.timeline-tasks.update', $row) }}" class="grid grid-cols-1 gap-4 md:grid-cols-2">
@csrf @method('PUT')
<div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Roadmap Period</label><select name="roadmap_period_id" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm">@foreach($periods as $p)<option value="{{ $p->id }}" @selected(old('roadmap_period_id',$row->roadmap_period_id)==$p->id)>{{ $p->project?->project_name }} | {{ $p->period }} | {{ $p->phase }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Sort</label><input name="sort_order" value="{{ old('sort_order',$row->sort_order) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Status</label><input name="task_status" value="{{ old('task_status',$row->task_status) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Task Text</label><textarea name="task_text" required class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm">{{ old('task_text',$row->task_text) }}</textarea></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Task Owner</label><input name="task_owner" value="{{ old('task_owner',$row->task_owner) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Original Owner</label><input name="original_owner" value="{{ old('original_owner',$row->original_owner) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Original Status</label><input name="original_status" value="{{ old('original_status',$row->original_status) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">PIC Actual Owner</label><input name="pic_actual_owner" value="{{ old('pic_actual_owner',$row->pic_actual_owner) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">PIC Start Date</label><input type="date" name="pic_start_date" value="{{ old('pic_start_date',optional($row->pic_start_date)->format('Y-m-d')) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">PIC Actual %</label><input type="number" step="0.01" min="0" max="100" name="pic_actual_percent" value="{{ old('pic_actual_percent',$row->pic_actual_percent) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Task Progress %</label><input type="number" step="0.01" min="0" max="100" name="task_progress_percent_normalized" value="{{ old('task_progress_percent_normalized',$row->task_progress_percent_normalized) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Target Date</label><input type="date" name="target_date" value="{{ old('target_date',optional($row->target_date)->format('Y-m-d')) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Evidence Link</label><input name="evidence_link" value="{{ old('evidence_link',$row->evidence_link) }}" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm"></div>
<div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">PIC Progress Note</label><textarea name="pic_progress_note" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm">{{ old('pic_progress_note',$row->pic_progress_note) }}</textarea></div>
<div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-on-surface-variant">Dependency Blocker</label><textarea name="dependency_blocker" class="w-full rounded-xl border border-outline-variant/30 bg-[#f8fafc] px-3 py-2.5 text-sm">{{ old('dependency_blocker',$row->dependency_blocker) }}</textarea></div>
<div class="md:col-span-2 flex gap-2 pt-2"><button class="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-xs font-bold text-white shadow-md">Perbarui</button> <a href="{{ route('pilot-project-validation.timeline-tasks.index') }}" class="inline-flex items-center gap-2 rounded-xl border border-outline-variant/30 bg-white px-4 py-2 text-xs font-bold shadow-sm hover:bg-surface-container-high">Kembali</a></div>
</form></div></div>
@endsection

